"""create initial schema

Revision ID: 92d5a06a6f79
Revises: 
Create Date: 2021-01-25 10:00:13.944750

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.schema import Sequence, CreateSequence

#field_seq = Sequence('trans_id_seq')
#op.execute(CreateSequence(Sequence('trans_id_seq')))

# revision identifiers, used by Alembic.
revision = '92d5a06a6f79'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dp_account',
    sa.Column('account_uid', sa.String(length=64), nullable=False),
    sa.Column('account_name', sa.String(length=32), nullable=False),
    sa.Column('account_deleted', sa.Boolean(), nullable=False),
    sa.Column('created_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('account_uid'),
    sa.UniqueConstraint('account_name')
    )
    op.create_table('dp_transaction',
    sa.Column('action_type', sa.String(length=32), nullable=False),
    sa.Column('account_uid', sa.String(length=64), nullable=False),
    sa.Column('account_enabled', sa.Boolean(), default=True,nullable=False),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('dual_send_enabled', sa.Boolean(), default=False,nullable=False),
    sa.Column('etl_enabled', sa.Boolean(), default=True, nullable=False),
    sa.Column('es_alt_endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('es_endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('index_rollover_policy_max_age_days', sa.Integer(), default=7, nullable=False),
    sa.Column('index_rollover_policy_max_doc_count', sa.Integer(), default=40000000,nullable=False),
    sa.Column('kbn_alt_endpoint_url', sa.String(length=512), nullable=True),
    sa.Column('kbn_endpoint_url', sa.String(length=512), nullable=False),
    sa.Column('last_known_good_enabled', sa.Boolean(), nullable=False),
    sa.Column('retention_period', sa.Integer(), default=30, nullable=False),
    sa.Column('transaction_id', sa.Integer(), nullable=False),
    sa.Column('updated_date', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('transaction_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('dp_transaction')
    op.drop_table('dp_account')
    # ### end Alembic commands ###
